import { describe,expect,test } from "bun:test";
import { scanCompany,type GigScoutHttpPort } from "..";
import type { platformAdapters } from "../contracts";
type Adapter=typeof platformAdapters[number];
const fixtures:Record<Adapter,{url:string;body:unknown}>={
  greenhouse:{url:"https://boards.greenhouse.io/example-labs",body:{jobs:[{id:101,title:"Reliability Gardener",absolute_url:"https://boards.greenhouse.io/example-labs/jobs/101",location:{name:"Remote"},content:"<p>Grow systems.</p>"}]}},
  lever:{url:"https://jobs.lever.co/example-labs",body:[{id:"role-1",text:"Reliability Gardener",hostedUrl:"https://jobs.lever.co/example-labs/role-1",categories:{location:"Remote"},description:"<p>Grow systems.</p>"}]},
  smartrecruiters:{url:"https://careers.smartrecruiters.com/ExampleLabs",body:{totalFound:1,content:[{id:"role-1",name:"Reliability Gardener",postingUrl:"https://jobs.smartrecruiters.com/ExampleLabs/role-1",location:{fullLocation:"Remote"},jobAd:{sections:{jobDescription:{text:"<p>Grow systems.</p>"}}}}]}},
  ashby:{url:"https://jobs.ashbyhq.com/example-labs",body:{jobs:[{id:"role-1",title:"Reliability Gardener",jobUrl:"https://jobs.ashbyhq.com/example-labs/role-1",location:"Remote",descriptionHtml:"<p>Grow systems.</p>"}]}},
  workday:{url:"https://example.wd1.myworkdayjobs.com/en-US/careers",body:{total:1,jobPostings:[{title:"Reliability Gardener",externalPath:"/job/role-1",locationsText:"Remote"}]}},
  "oracle-hcm":{url:"https://hcm.example.test/hcmUI/CandidateExperience/en/sites/CX_1",body:{count:1,items:[{requisitionList:[{Id:"role-1",Title:"Reliability Gardener",ExternalCareerSiteURL:"https://hcm.example.test/jobs/role-1",PrimaryLocation:"Remote",ShortDescriptionStr:"Grow systems."}]}]}},
  adp:{url:"https://myjobs.adp.com/example-labs/cx",body:{totalCount:1,jobRequisitions:[{reqId:"role-1",publishedJobTitle:"Reliability Gardener",jobUrl:"https://myjobs.adp.com/example-labs/jobs/role-1",jobDescription:"Grow systems."}]}},
  eightfold:{url:"https://talent.example.test/careers?domain=example.test",body:{status:200,data:{total:1,positions:[{id:"role-1",name:"Reliability Gardener",positionUrl:"/careers/role-1",standardizedLocations:["Remote"]}]}}},
  jibe:{url:"https://careers.example.test/search",body:{total:1,jobs:[{data:{slug:"role-1",language:"en-us",title:"Reliability Gardener",city:"Remote",description:"Grow systems."}}]}},
  "successfactors-rmk":{url:"https://careers.example.test/services/recruiting/v1/jobs?locale=en_US",body:{totalResults:1,jobSearchResult:[{response:{id:"role-1",title:"Reliability Gardener",url:"/job/role-1",location:"Remote"}}]}},
  gem:{url:"https://jobs.gem.com/example-labs",body:{data:{oatsExternalJobPostings:{jobPostings:[{id:"role-1",extId:"role-1",title:"Reliability Gardener",descriptionHtml:"Grow systems.",locations:[{name:"Remote",isRemote:true}]}]}}}},
};
describe("generic platform adapters",()=>{
  for(const [adapter,fixture] of Object.entries(fixtures) as Array<[Adapter,(typeof fixtures)[Adapter]]>)test(`${adapter} plans and normalizes its official API`,async()=>{let requested="",calls=0;const http:GigScoutHttpPort={async request(input){requested=input.url;calls++;return{status:200,url:input.url,headers:{},body:adapter==="adp"&&calls===1?JSON.stringify({myJobsToken:"synthetic-token",properties:{myadpUrl:"https://my.adp.example.test"}}):JSON.stringify(fixture.body)};}};const result=await scanCompany({companyId:"company-1",configurationVersionId:"config-1",sources:[{key:"official",type:"platform",adapter,url:fixture.url,active:true,maxPages:2,searchTerms:[]}]},{http});expect(requested).toStartWith("https://");expect(result.sources[0]?.status).toBe("succeeded_with_results");expect(result.positions[0]?.title).toBe("Reliability Gardener");expect(result.positions[0]?.canonicalUrl).toStartWith("https://");if(adapter==="adp")expect(result.sources[0]?.attempts[0]).toMatchObject({requestCount:2,responseCount:2});});
  for(const [adapter,fixture] of Object.entries(fixtures) as Array<[Adapter,(typeof fixtures)[Adapter]]>)test(`${adapter} treats a changed response surface as suspicious`,async()=>{const http:GigScoutHttpPort={async request(input){return{status:200,url:input.url,headers:{},body:"{}"};}};const result=await scanCompany({companyId:"company-1",configurationVersionId:"config-1",sources:[{key:"official",type:"platform",adapter,url:fixture.url,active:true,maxPages:1,searchTerms:[]}]},{http});expect(result.sources[0]?.status).toBe(adapter==="adp"?"failed":"suspicious_empty");});
  test("Workday preserves public and API detail identities",async()=>{const fixture=fixtures.workday;const result=await scanCompany({companyId:"company-1",configurationVersionId:"config-1",sources:[{key:"official",type:"platform",adapter:"workday",url:"https://example.wd1.myworkdayjobs.com/en-US/External",active:true,maxPages:1,searchTerms:[]}]},{http:{async request(input){return{status:200,url:input.url,headers:{},body:JSON.stringify(fixture.body)};}}});expect(result.positions[0]?.canonicalUrl).toBe("https://example.wd1.myworkdayjobs.com/External/job/role-1");expect(result.positions[0]?.provenance.descriptionUrl).toBe("https://example.wd1.myworkdayjobs.com/wday/cxs/example/External/job/role-1");});
  test("search terms each start at page one and paginate independently",async()=>{const requests:string[]=[];const bodies:string[]=[];const result=await scanCompany({companyId:"company-1",configurationVersionId:"config-1",sources:[{key:"official",type:"platform",adapter:"workday",url:"https://example.wd1.myworkdayjobs.com/en-US/External",active:true,maxPages:3,searchTerms:["garden","orchard"]}]},{http:{async request(input){requests.push(input.url);bodies.push(input.body??"");const body=JSON.parse(input.body??"{}") as {offset:number;searchText:string};return{status:200,url:input.url,headers:{},body:JSON.stringify({total:body.offset===0?21:21,jobPostings:body.offset===0?Array.from({length:20},(_,index)=>({title:`${body.searchText}-${index}`,externalPath:`/job/${body.searchText}-${index}`})):[{title:`${body.searchText}-20`,externalPath:`/job/${body.searchText}-20`}]})};}}});expect(requests).toHaveLength(4);expect(bodies.map(value=>JSON.parse(value))).toEqual([{appliedFacets:{},limit:20,offset:0,searchText:"garden"},{appliedFacets:{},limit:20,offset:20,searchText:"garden"},{appliedFacets:{},limit:20,offset:0,searchText:"orchard"},{appliedFacets:{},limit:20,offset:20,searchText:"orchard"}]);expect(result.positions).toHaveLength(42);});
  test("SuccessFactors RMK uses its POST payload and required referer",async()=>{let request:Parameters<GigScoutHttpPort["request"]>[0]|undefined;await scanCompany({companyId:"company-1",configurationVersionId:"config-1",sources:[{key:"official",type:"platform",adapter:"successfactors-rmk",url:fixtures["successfactors-rmk"].url,active:true,maxPages:1,searchTerms:["gardener"]}]},{http:{async request(input){request=input;return{status:200,url:input.url,headers:{},body:JSON.stringify(fixtures["successfactors-rmk"].body)};}}});expect(request?.method).toBe("POST");expect(request?.headers?.referer).toContain("q=gardener");expect(JSON.parse(request?.body??"{}")).toMatchObject({keywords:"gardener",pageNumber:0});});
  test("ADP discovers the private listing API from the public career-site configuration",async()=>{const requests:Array<Parameters<GigScoutHttpPort["request"]>[0]>=[];await scanCompany({companyId:"company-1",configurationVersionId:"config-1",sources:[{key:"official",type:"platform",adapter:"adp",url:fixtures.adp.url,active:true,maxPages:1,searchTerms:[]}]},{http:{async request(input){requests.push(input);return{status:200,url:input.url,headers:{},body:requests.length===1?JSON.stringify({myJobsToken:"synthetic-token",properties:{myadpUrl:"https://my.adp.example.test"}}):JSON.stringify(fixtures.adp.body)};}}});expect(requests).toHaveLength(2);expect(requests[1]?.url).toContain("apply-custom-filters");expect(requests[1]?.headers).toMatchObject({myjobstoken:"synthetic-token",rolecode:"manager"});});
});
