import type { AuditQuery } from "./services";
import type { BusinessEventInput, ChangeContext, ChangeResult, EntityRecord, JobData, JobPersonData, MeetingData, NetworkingContactData, PersonData, RevertedRecord, TaskData } from "./models";

export interface ReadRepository<T extends {id:string}>{get(id:string,options?:{includeDeleted?:boolean}):EntityRecord<T>|null;list(options?:{includeDeleted?:boolean}):EntityRecord<T>[]}
export interface WriteRepository<T extends {id:string}> extends ReadRepository<T>{create(record:T):EntityRecord<T>;update(id:string,revision:number,patch:Partial<Omit<T,"id">>):EntityRecord<T>;delete(id:string,revision:number):EntityRecord<T>;restore(id:string,revision:number,patch:Partial<Omit<T,"id">>):EntityRecord<T>}
export interface UnitOfWork{jobs:WriteRepository<JobData>;people:WriteRepository<PersonData>;networking:WriteRepository<NetworkingContactData>;jobPeople:WriteRepository<JobPersonData>;tasks:WriteRepository<TaskData>;meetings:WriteRepository<MeetingData>;recordEvent(input:BusinessEventInput):string}
export interface Persistence{jobs:ReadRepository<JobData>;people:ReadRepository<PersonData>;networking:ReadRepository<NetworkingContactData>;jobPeople:ReadRepository<JobPersonData>;tasks:ReadRepository<TaskData>;meetings:ReadRepository<MeetingData>;change<T>(context:ChangeContext,action:(transaction:UnitOfWork)=>T):ChangeResult<T>;revertChange(context:ChangeContext,targetChangeId:string):ChangeResult<RevertedRecord[]>}
export interface AuditPort{query(query:AuditQuery):Record<string,unknown>|Record<string,unknown>[]|null}
export interface ArtifactPort{personProfile(personId:string):Promise<string>;jobDescription(jobId:string):Promise<string>;interviewPrep(jobId:string):Promise<{name:string;content:string}[]>;personProfileExists(personId:string):Promise<boolean>;jobDescriptionExists(jobId:string):Promise<boolean>;interviewPrepExists(jobId:string):Promise<boolean>;verify(expectations:{people:{id:string;hasLocalProfile:boolean}[];jobs:{id:string;hasJobDescription:boolean;hasInterviewPrep:boolean}[]}):Promise<ArtifactVerification>}
export interface ArtifactVerification{ok:boolean;errors:string[];unregistered:string[]}
