import type { ArtifactPort, AuditPort, Persistence, ReadRepository, UnitOfWork, WriteRepository } from "./ports";
import type { BusinessEventInput, ChangeContext, EntityName, EntityRecord, JobPersonData, MeetingData, PersonData } from "./models";

export type AuditQuery={resource:"change";id:string}|{resource:"history";entity:EntityName;id:string}|{resource:"events";entityType?:string;entityId?:string};

class EntityService<T extends{id:string}>{constructor(protected readonly persistence:Persistence,protected readonly repository:ReadRepository<T>,private readonly writable:(u:UnitOfWork)=>WriteRepository<T>){}get(id:string,options:{includeDeleted?:boolean}={}){return this.repository.get(id,options)}list(options:{includeDeleted?:boolean}={}){return this.repository.list(options)}create(context:ChangeContext,record:T){return this.persistence.change(context,u=>this.writable(u).create(record)).value}update(context:ChangeContext,id:string,revision:number,patch:Partial<Omit<T,"id">>){return this.persistence.change(context,u=>this.writable(u).update(id,revision,patch)).value}protected updateIncludingDeleted(context:ChangeContext,record:EntityRecord<T>,patch:Partial<Omit<T,"id">>){return this.persistence.change(context,u=>{const repository=this.writable(u);if(!record.isDeleted)return repository.update(record.id,record.revision,patch);const restored=repository.restore(record.id,record.revision,patch);return repository.delete(record.id,restored.revision)}).value}}

export class PeopleService extends EntityService<PersonData>{constructor(p:Persistence,private readonly artifacts:ArtifactPort){super(p,p.people,u=>u.people)}async profile(id:string){const person=this.get(id);if(!person)throw new Error(`Person not found: ${id}`);if(!person.hasLocalProfile)return null;return this.artifacts.personProfile(id)}patch(context:ChangeContext,id:string,patch:Partial<Omit<PersonData,"id">>,options:{dryRun?:boolean}={}){const person=this.get(id);if(!person)throw new Error(`Person not found: ${id}`);return options.dryRun?{...person,...patch}:super.update(context,id,person.revision,patch)}syncProfileFlag(context:ChangeContext,record:EntityRecord<PersonData>,present:boolean){return this.updateIncludingDeleted(context,record,{hasLocalProfile:present})}}
export class MeetingService extends EntityService<MeetingData>{constructor(p:Persistence){super(p,p.meetings,u=>u.meetings)}}
export class EventService{constructor(private readonly persistence:Persistence){}record(context:ChangeContext,event:BusinessEventInput){return this.persistence.change(context,u=>u.recordEvent(event)).value}}
export class JobPeopleService extends EntityService<JobPersonData>{constructor(p:Persistence){super(p,p.jobPeople,u=>u.jobPeople)}forJob(jobId:string){return this.list().filter(item=>item.jobId===jobId)}}
export class HistoryService{constructor(private readonly audit:AuditPort){}change(id:string){return this.audit.query({resource:"change",id})}entity(entity:EntityName,id:string){return this.audit.query({resource:"history",entity,id})}events(entityType?:string,entityId?:string){return this.audit.query({resource:"events",entityType,entityId})}}
