import { describe,expect,test } from "bun:test";
import { GigFinderApplication } from "../application";
import { ChangeExecutor } from "../changes";
import { DomainValidationError,MutationError,OptimisticConcurrencyError } from "../errors";
import type { ArtifactPort,ArtifactVerification,AuditPort,DocumentWriteRepository,Persistence,ReadRepository,UnitOfWork } from "../ports";
import type { ChangeContext,EntityRecord,GigData,GigPersonData,MeetingData,MeetingParticipantData,PersonData,TaskData } from "../models";
import { documentDisplayName,type DocumentLinkEntityType,type ManagedDocumentData,type ManagedDocumentRecord,type ManagedDocumentVersionData } from "../documents";

const metadata={revision:1,isDeleted:false,createdAt:"2026-07-22T12:00:00-07:00",updatedAt:"2026-07-22T12:00:00-07:00"};
class Repo<T extends{id:string}> implements ReadRepository<T>{rows=new Map<string,EntityRecord<T>>();get(id:string){return this.rows.get(id)??null}list(){return[...this.rows.values()]}create(record:T){const value={...record,...metadata};this.rows.set(record.id,value);return value}update(id:string,revision:number,patch:Partial<Omit<T,"id">>){const current=this.get(id)!;const value={...current,...patch,revision:revision+1,updatedAt:"2026-07-23T12:00:00-07:00"};this.rows.set(id,value);return value}touch(id:string,revision:number){return this.update(id,revision,{})}delete(id:string){return this.rows.get(id)!}restore(id:string){return this.rows.get(id)!}}
const gigs=new Repo<GigData>(),people=new Repo<PersonData>(),gigPeople=new Repo<GigPersonData>(),tasks=new Repo<TaskData>(),meetings=new Repo<MeetingData>(),meetingParticipants=new Repo<MeetingParticipantData>();
const personData=(identity:Pick<PersonData,"id"|"name"|"company"|"title"|"linkedInProfileUrl"|"connectedOn">):PersonData=>({...identity,relationshipType:"professional_contact",relationshipStrength:"unknown",introducedBy:null,relationshipNotes:null,priority:"unranked",status:"not_contacted",lastContacted:null,lastContactMethod:null,lastContactSummary:null,nextAction:null,nextActionDue:null,whyInteresting:null,notesJson:"[]",tagsJson:"[]"});
class DocumentRepo implements DocumentWriteRepository {
  rows=new Map<string,ManagedDocumentRecord>();histories=new Map<string,ManagedDocumentVersionData[]>();
  get(id:string){return this.rows.get(id)??null}
  list(entityType:DocumentLinkEntityType,entityId:string){return[...this.rows.values()].filter(document=>document.links.some(link=>link.entityType===entityType&&link.entityId===entityId))}
  listVersions(id:string){return this.histories.get(id)??[]}
  create(input:{document:ManagedDocumentData;content:string;contentHash:string}){const record={...input.document,displayName:documentDisplayName(input.document),currentVersion:1,content:input.content,contentHash:input.contentHash,createdAt:metadata.createdAt,updatedAt:metadata.updatedAt};this.rows.set(record.id,record);this.histories.set(record.id,[{documentId:record.id,version:1,parentVersion:null,content:record.content,contentHash:record.contentHash,changeId:"test-change",changeSummary:"change",createdAt:record.createdAt,createdBy:"test"}]);return record}
  addVersion(input:{documentId:string;expectedVersion:number;content:string;contentHash:string;changeSummary:string}){const current=this.get(input.documentId)!;const version=input.expectedVersion+1;const record={...current,currentVersion:version,content:input.content,contentHash:input.contentHash,updatedAt:"2026-07-23T12:00:00-07:00"};this.rows.set(record.id,record);this.histories.set(record.id,[{documentId:record.id,version,parentVersion:input.expectedVersion,content:record.content,contentHash:record.contentHash,changeId:"test-change",changeSummary:input.changeSummary,createdAt:record.updatedAt,createdBy:"test"},...(this.histories.get(record.id)??[])]);return record}
}
const documents=new DocumentRepo();
const recordedEvents:string[]=[];
const persistence:Persistence={gigs,people,gigPeople,tasks,meetings,meetingParticipants,documents,settings:{get:()=>null,set:()=>undefined},hasChange:()=>false,creationFingerprint:()=>null,change:(context,action)=>({changeId:context.changeId??`test-${context.summary}`,value:action({gigs,people,gigPeople,tasks,meetings,meetingParticipants,documents,recordCreationFingerprint:()=>undefined,recordEvent:event=>{recordedEvents.push(event.id??event.type);return event.id??event.type}} as UnitOfWork)}),revertChange:(revertContext,targetChangeId)=>({changeId:revertContext.changeId??`revert-${targetChangeId}`,value:[{entity:"gig",id:"gig"}]})};
const artifacts:ArtifactPort={jobDescription:async()=>"description",interviewPrep:async()=>[{name:"general.md",content:"prep"}],jobDescriptionExists:async()=>true,interviewPrepExists:async()=>true,verify:async():Promise<ArtifactVerification>=>({ok:true,errors:[],unregistered:[]})};
const audit:AuditPort={query:query=>({query})};const app=new GigFinderApplication(persistence,audit,artifacts);const context:ChangeContext={actor:"test",source:"test",summary:"change"};
describe("application services",()=>{
 test("shared creation contracts create complete gigs, people, and validated relationships",()=>{
  const gig=app.gigs.createNew({...context,changeId:"create-gig"},"contract-gig",{company:"Contract Co",title:"Director",externalJobId:null,stage:"identified",outcome:"pending",statusSummary:"Identified",lastActivity:"2026-08-05",nextAction:null,fit:{rating:"good",summary:null},payRange:null,sourceUrl:null,tags:[],location:null,workArrangement:null,postedDate:null,businessUnitTeam:null,recruiterSource:null,bonus:null,equity:null,otherCompensation:null});
  expect(gig).toMatchObject({changeId:"create-gig",record:{id:"contract-gig",documents:[]}});
  const person=app.people.createNew({...context,changeId:"create-person"},"contract-person",{name:"Casey Example",company:"Contract Co",title:"Recruiter",linkedInProfileUrl:null,connectedOn:null});
  expect(person).toMatchObject({changeId:"create-person",record:{id:"contract-person",priority:"unranked",status:"not_contacted"}});
  const relationship=app.gigPeople.createNew({...context,changeId:"create-relationship"},"contract-relationship",{gigId:"contract-gig",personId:"contract-person",relationship:"recruiter",notes:null});
  expect(relationship).toMatchObject({changeId:"create-relationship",record:{relationship:"recruiter"}});
  expect(()=>app.gigPeople.createNew(context,"duplicate-relationship",{gigId:"contract-gig",personId:"contract-person",relationship:"recruiter",notes:null})).toThrow("Relationship already exists");
  expect(()=>app.gigPeople.createNew(context,"missing-relationship",{gigId:"missing",personId:"contract-person",relationship:"recruiter",notes:null})).toThrow("Gig not found");
 });
 test("gig service reads, writes, and loads artifacts",async()=>{app.gigs.create(context,{id:"gig",company:"Company",title:"VP",externalJobId:null,artifactDirectory:null,stage:"identified",outcome:"pending",statusSummary:"Found",lastActivity:"2026-07-22",nextAction:null,fit:{rating:"good",summary:null},payRange:null,sourceUrl:null,tags:[],hasJobDescription:true,hasInterviewPrep:true});expect(app.gigs.get("gig")?.company).toBe("Company");expect(await app.gigs.description("gig")).toBe("description");expect(await app.gigs.prep("gig")).toHaveLength(1)});
 test("people service stores canonical people with neutral relationship defaults",()=>{app.people.create(context,{id:"person",name:"Person",company:null,title:null,linkedInProfileUrl:null,connectedOn:null});expect(app.people.get("person")).toMatchObject({name:"Person",relationship:{type:"professional_contact",strength:"unknown"},priority:"unranked",status:"not_contacted",outreach:{lastContacted:null,nextAction:null},notes:[],tags:[]})});
 test("people service includes relationship and outreach state",()=>{app.people.create(context,{id:"network-person",name:"Network Person",company:null,title:null,linkedInProfileUrl:null,connectedOn:null,relationshipType:"colleague",relationshipStrength:"warm",priority:"high",status:"not_contacted"});expect(app.people.get("network-person")).toMatchObject({name:"Network Person",relationship:{type:"colleague",strength:"warm"},priority:"high"})});
 test("task service creates and updates tasks",()=>{const created=app.tasks.createNew({...context,occurredAt:"2026-07-22T12:00:00-07:00"},{id:"task",title:"Task",type:"other",dueDate:null,relatedEntity:{type:"general",id:null},notes:null});expect(app.tasks.complete(context,created.record.id,"2026-07-22").status).toBe("completed")});
 test("meeting service stores meetings",()=>{if(!people.get("person"))people.create(personData({id:"person",name:"Person",company:null,title:null,linkedInProfileUrl:null,connectedOn:null}));app.meetings.create(context,{id:"meeting",title:"Coffee",startsAt:"2026-07-22T12:00:00-07:00",endsAt:"2026-07-22T13:00:00-07:00",timezone:"America/Los_Angeles",location:null,description:null,status:"confirmed",gigId:null,personIds:["person"],externalCalendarId:null,externalEventId:null});expect(app.meetings.list()).toHaveLength(1)});
 test("meeting participant IDs remain distinct when domain IDs contain delimiters",()=>{people.create(personData({id:"b::c",name:"First Person",company:null,title:null,linkedInProfileUrl:null,connectedOn:null}));people.create(personData({id:"c",name:"Second Person",company:null,title:null,linkedInProfileUrl:null,connectedOn:null}));const base={title:"Conversation",startsAt:"2026-07-22T12:00:00-07:00",endsAt:"2026-07-22T13:00:00-07:00",timezone:"America/Los_Angeles",location:null,description:null,status:"confirmed" as const,gigId:null,externalCalendarId:null,externalEventId:null};app.meetings.create(context,{...base,id:"a",personIds:["b::c"]});app.meetings.create(context,{...base,id:"a::b",personIds:["c"]});expect(meetingParticipants.list().filter(record=>record.meetingId==="a"||record.meetingId==="a::b").map(record=>record.id).sort()).toEqual(["meeting-participant:1:ab::c","meeting-participant:4:a::bc"])});
 test("meeting creation compares start and end as absolute instants",()=>{if(!people.get("timestamp-person"))people.create(personData({id:"timestamp-person",name:"Timestamp Person",company:null,title:null,linkedInProfileUrl:null,connectedOn:null}));const base={title:"Offset meeting",timezone:"America/Los_Angeles",location:null,description:null,status:"confirmed" as const,gigId:null,personIds:["timestamp-person"],externalCalendarId:null,externalEventId:null};expect(()=>app.meetings.create(context,{...base,id:"valid-offset-meeting",startsAt:"2026-07-20T23:00:00+09:00",endsAt:"2026-07-20T08:00:00-07:00"})).not.toThrow();expect(()=>app.meetings.create(context,{...base,id:"invalid-offset-meeting",startsAt:"2026-07-20T08:00:00-07:00",endsAt:"2026-07-20T23:00:00+09:00"})).toThrow("must end at or after it starts");expect(()=>app.meetings.create(context,{...base,id:"invalid-timestamp-meeting",startsAt:"not-a-date",endsAt:"2026-07-20T23:00:00+09:00"})).toThrow("requires valid ISO 8601 timestamps")});
 test("meeting creation requires an IANA timezone",()=>{if(!people.get("timezone-person"))people.create(personData({id:"timezone-person",name:"Timezone Person",company:null,title:null,linkedInProfileUrl:null,connectedOn:null}));expect(()=>app.meetings.create(context,{id:"invalid-timezone-meeting",title:"Coffee",startsAt:"2026-07-22T12:00:00-07:00",endsAt:"2026-07-22T13:00:00-07:00",timezone:"Mars/Olympus",location:null,description:null,status:"confirmed",gigId:null,personIds:["timezone-person"],externalCalendarId:null,externalEventId:null})).toThrow("must be a valid IANA timezone")});
 test("meeting updates use the shared domain contract and return the audited change",()=>{if(!people.get("meeting-person-1"))people.create(personData({id:"meeting-person-1",name:"First Person",company:null,title:null,linkedInProfileUrl:null,connectedOn:null}));if(!people.get("meeting-person-2"))people.create(personData({id:"meeting-person-2",name:"Second Person",company:null,title:null,linkedInProfileUrl:null,connectedOn:null}));app.meetings.create(context,{id:"meeting-update",title:"Coffee",startsAt:"2026-07-22T12:00:00-07:00",endsAt:"2026-07-22T13:00:00-07:00",timezone:"America/Los_Angeles",location:"Seattle",description:null,status:"confirmed",gigId:null,personIds:["meeting-person-1"],externalCalendarId:null,externalEventId:null});const updated=app.meetings.update({...context,changeId:"meeting-update-change"},"meeting-update",{status:"completed",personIds:["meeting-person-1","meeting-person-2"],location:null});expect(updated).toMatchObject({changeId:"meeting-update-change",record:{status:"completed",personIds:["meeting-person-1","meeting-person-2"],location:null}});expect(app.meetings.get("meeting-update")).toMatchObject({status:"completed",personIds:["meeting-person-1","meeting-person-2"],location:null});expect(()=>app.meetings.update(context,"meeting-update",{endsAt:"2026-07-22T11:00:00-07:00"})).toThrow("must end at or after it starts")});
 test("gig-people service filters relationships",()=>{app.gigPeople.create(context,{id:"relation",gigId:"gig",personId:"person",relationship:"interviewer",notes:null});const result=app.gigPeople.query({gigIds:["gig"]});expect(result.status==="ok"?result.items:[]).toHaveLength(1)});
 test("event service records sourced business events",()=>{expect(app.events.record(context,{id:"event",type:"message_received",entityType:"gig",entityId:"gig",occurredAt:"2026-07-22T12:00:00-07:00",summary:"Recruiter wrote",sources:[{sourceSystem:"linkedin",importedAt:"2026-07-22T12:00:00-07:00"}]})).toBe("event");expect(recordedEvents).toContain("event")});
 test("history service delegates audit queries",()=>{expect(app.history.entity("gig","gig")).toBeTruthy()});
 test("managed document service creates immutable versions and deduplicates identical content",async()=>{
  if(!app.gigs.get("gig"))app.gigs.create(context,{id:"gig",company:"Company",title:"VP",externalJobId:null,artifactDirectory:null,stage:"identified",outcome:"pending",statusSummary:"Found",lastActivity:"2026-07-22",nextAction:null,fit:{rating:"good",summary:null},payRange:null,sourceUrl:null,tags:[],hasJobDescription:true,hasInterviewPrep:true});
  const created=app.documents.create({...context,changeId:"document-create"},{links:[{entityType:"gig",entityId:"gig"}],documentType:"job_description",title:"Job description",mediaType:"text/plain",sourceDescription:"Provided by the user",content:"Original description"});
  expect(created).toMatchObject({changed:true,changeId:"document-create",document:{currentVersion:1,content:"Original description"}});
  const gigDetail=app.gigs.read("gig");
  expect(gigDetail.status).toBe("ok");
  expect(gigDetail.status==="ok" ? gigDetail.record.documents : []).toContainEqual(expect.objectContaining({id:created.document.id,type:"job_description"}));
  expect(await app.documentReader.get(created.document.id)).toMatchObject({status:"ok",record:{content:"Original description"}});
  const unchanged=app.documents.update({...context,changeId:"document-noop"},{documentId:created.document.id,expectedVersion:1,content:"Original description",changeSummary:"No content change"});
  expect(unchanged).toMatchObject({changed:false,changeId:null,document:{currentVersion:1}});
  const updated=app.documents.update({...context,changeId:"document-update"},{documentId:created.document.id,expectedVersion:1,content:"Corrected description",changeSummary:"Correct source text"});
  expect(updated).toMatchObject({changed:true,changeId:"document-update",document:{currentVersion:2,content:"Corrected description"}});
  expect(app.documents.versions(created.document.id).map(version=>version.content)).toEqual(["Corrected description","Original description"]);
 expect(await app.documentReader.get(created.document.id)).toMatchObject({status:"ok",record:{content:"Corrected description"}});
  const discovery=await app.documentReader.query({owner:{entityType:"gig",entityId:"gig"},offset:0,limit:50});
  expect(discovery).toMatchObject({status:"ok",page:{limit:50,total:3}});
  expect(discovery.status==="ok"?discovery.items:[]).toContainEqual(expect.objectContaining({reference:created.document.id,storage:"managed"}));
  const versionPage=app.documentReader.versionQuery({documentId:created.document.id,offset:0,limit:1});
  expect(versionPage).toMatchObject({status:"ok",page:{limit:1,total:2},items:[{version:2}]});
  expect(versionPage.status==="ok"?versionPage.items[0]:null).not.toHaveProperty("content");
  expect(app.documentReader.versionQuery({documentId:"gig:gig:job_description"})).toMatchObject({status:"unsupported"});
 expect(()=>app.documents.update(context,{documentId:created.document.id,expectedVersion:1,content:"Stale description",changeSummary:"Stale update"})).toThrow(new MutationError("revision_conflict",`Document ${created.document.id} expected version 1 but is at version 2.`));
 });
 test("uploaded source documents preserve provenance and cannot be edited",()=>{
  if(!app.gigs.get("gig"))app.gigs.create(context,{id:"gig",company:"Company",title:"VP",externalJobId:null,artifactDirectory:null,stage:"identified",outcome:"pending",statusSummary:"Found",lastActivity:"2026-07-22",nextAction:null,fit:{rating:"good",summary:null},payRange:null,sourceUrl:null,tags:[],hasJobDescription:true,hasInterviewPrep:true});
  const provenance={originalFilename:"role.pdf",detectedMediaType:"application/pdf" as const,sourceContentHash:"a".repeat(64),converter:"pdfjs-dist",converterVersion:"6.2.108",extractionWarnings:[],uploadedAt:"2026-07-29T12:00:00.000Z"};
  const created=app.documents.create({...context,changeId:"uploaded-document-create"},{links:[{entityType:"gig",entityId:"gig"}],documentType:"job_description",title:"Uploaded job description",mediaType:"text/markdown",sourceDescription:null,content:"Exact converted source",uploadProvenance:provenance});
  expect(created.document.uploadProvenance).toEqual(provenance);
  expect(()=>app.documents.update(context,{documentId:created.document.id,expectedVersion:1,content:"Rewritten source",changeSummary:"Rewrite"})).toThrow(new DomainValidationError("Uploaded source documents are immutable and cannot be updated."));
 });
 test("profiles link to exactly one person and appear on every related record",()=>{
  if(!app.gigs.get("gig"))app.gigs.create(context,{id:"gig",company:"Company",title:"VP",externalJobId:null,artifactDirectory:null,stage:"identified",outcome:"pending",statusSummary:"Found",lastActivity:"2026-07-22",nextAction:null,fit:{rating:"good",summary:null},payRange:null,sourceUrl:null,tags:[]});
  const person=app.people.get("network-person")??app.people.create(context,{id:"network-person",name:"Network Person",company:"Company",title:"Director",linkedInProfileUrl:null,connectedOn:null,relationshipType:"colleague",relationshipStrength:"warm",priority:"high",status:"active_relationship"});
  const created=app.documents.create(context,{links:[{entityType:"person",entityId:person.id},{entityType:"gig",entityId:"gig"}],documentType:"profile",title:null,mediaType:"text/markdown",sourceDescription:null,content:"Person profile"});
  expect(created.document.displayName).toBe("Profile");
  expect(app.gigs.get("gig")?.documents).toContainEqual({id:created.document.id,type:"profile",title:null,displayName:"Profile"});
  expect(app.people.get(person.id)).toMatchObject({hasProfile:true,documents:[{id:created.document.id,type:"profile",title:null,displayName:"Profile"}]});
  expect(()=>app.documents.create(context,{links:[{entityType:"gig",entityId:"gig"}],documentType:"profile",title:null,mediaType:"text/markdown",sourceDescription:null,content:"Missing person"})).toThrow(new DomainValidationError("A profile must link to exactly one person."));
 });
 test("shared gig service returns complete models and preserves fields on patch",()=>{const gig=app.gigs.create(context,{id:"complete-gig",company:"Company",title:"VP Engineering",externalJobId:"123",artifactDirectory:null,stage:"identified",outcome:"pending",statusSummary:"Found",lastActivity:"2026-07-22",nextAction:null,fit:{rating:"good",summary:null},payRange:null,sourceUrl:null,tags:[],hasJobDescription:false,hasInterviewPrep:false,location:"Seattle",workArrangement:"hybrid",postedDate:"2026-07-20",businessUnitTeam:"Platform",recruiterSource:"Referral",bonus:"20%",equity:"RSUs",otherCompensation:null});expect(gig.location).toBe("Seattle");const updated=app.gigs.update(context,gig.id,{stage:"applied",statusSummary:"Applied"});expect(updated.record).toMatchObject({stage:"applied",location:"Seattle",workArrangement:"hybrid",bonus:"20%",equity:"RSUs"});expect(updated.changeId).toBe("test-change");expect(gigs.get(gig.id)).toMatchObject({location:"Seattle",workArrangement:"hybrid",bonus:"20%",equity:"RSUs"})});
 test("gig updates return the caller-supplied audited change",()=>{app.gigs.create(context,{id:"updated-gig",company:"Company",title:"Director",externalJobId:null,artifactDirectory:null,stage:"identified",outcome:"pending",statusSummary:"Found",lastActivity:"2026-07-22",nextAction:null,fit:{rating:"good",summary:null},payRange:null,sourceUrl:null,tags:[]});const result=app.gigs.update({...context,changeId:"change-1"},"updated-gig",{stage:"applied",statusSummary:"Applied"});expect(result).toMatchObject({changeId:"change-1",record:{stage:"applied",statusSummary:"Applied"}});expect(app.gigs.get("updated-gig")?.stage).toBe("applied")});
 test("dry-run updates return a candidate without an audit change",()=>{app.gigs.create(context,{id:"preview-gig",company:"Company",title:"Director",externalJobId:null,artifactDirectory:null,stage:"identified",outcome:"pending",statusSummary:"Found",lastActivity:"2026-07-22",nextAction:null,fit:{rating:"good",summary:null},payRange:null,sourceUrl:null,tags:[]});const result=app.gigs.update(context,"preview-gig",{statusSummary:"Preview"},{dryRun:true});expect(result).toMatchObject({changeId:null,record:{statusSummary:"Preview"}});expect(app.gigs.get("preview-gig")?.statusSummary).toBe("Found")});
 test("change reversal is a client-neutral application capability",()=>{expect(app.changes.revert({actor:"candidate",source:"user_request",summary:"Undo update",changeId:"revert-1"},"change-from-cli")).toEqual({changeId:"revert-1",revertedChangeId:"change-from-cli",affected:[{entity:"gig",id:"gig"}]})});
 test("change execution translates persistence concurrency failures",()=>{const conflictPersistence={...persistence,change:()=>{throw new OptimisticConcurrencyError("Gig gig expected revision 1, actual revision 2")}} satisfies Persistence;const executor=new ChangeExecutor(conflictPersistence);try{executor.execute(context,{id:"gig"},{},()=>({id:"gig"}));throw new Error("Expected conflict")}catch(error){expect(error).toBeInstanceOf(MutationError);expect((error as MutationError).code).toBe("revision_conflict");expect((error as Error).cause).toBeInstanceOf(OptimisticConcurrencyError)}});
 test("rejects contradictory gig stage and outcome states with clear domain errors",()=>{const gig={id:"invalid-gig",company:"Company",title:"VP Engineering",externalJobId:null,artifactDirectory:null,stage:"identified" as const,outcome:"pending" as const,statusSummary:"Found",lastActivity:"2026-07-22",nextAction:null,fit:{rating:"good" as const,summary:null},payRange:null,sourceUrl:null,tags:[],hasJobDescription:false,hasInterviewPrep:false};expect(()=>app.gigs.create(context,{...gig,stage:"closed"})).toThrow(new DomainValidationError("Gig invalid-gig cannot be closed while its outcome is pending."));expect(()=>app.gigs.create(context,{...gig,outcome:"rejected"})).toThrow(new DomainValidationError("Gig invalid-gig must remain pending until its stage is closed."))});
 test("shared person service updates identity and outreach in one revision",()=>{const person=app.people.create(context,{id:"shared-person",name:"Shared Person",company:"Company",title:"Director",linkedInProfileUrl:null,connectedOn:null,relationshipType:"former_colleague",relationshipStrength:"warm",priority:"high",status:"not_contacted"});const updated=app.people.update(context,person.id,{status:"outreach_sent",outreach:{lastContacted:"2026-07-23",lastContactMethod:"linkedin",lastContactSummary:"Sent a note"}});const persisted=app.people.get(person.id);if(!persisted)throw new Error("Expected persisted person");expect(updated.record.outreach.lastContactSummary).toBe("Sent a note");expect(updated.record.updatedAt).toBe("2026-07-23");expect(updated.record).toEqual(persisted);expect(people.get(person.id)).toMatchObject({name:"Shared Person",status:"outreach_sent",revision:2})});
 test("shared task service owns defaults, completion, and dry runs",()=>{const task=app.tasks.createNew({...context,occurredAt:"2026-07-22T12:00:00-07:00"},{id:"shared-task",title:"Follow up",type:"networking_follow_up",dueDate:"2026-07-24",relatedEntity:{type:"general",id:null},notes:null});expect(task.record).toMatchObject({status:"open",priority:"medium"});expect(app.tasks.complete(context,task.record.id,"2026-07-23")).toMatchObject({status:"completed",completedAt:"2026-07-23"});const preview=app.tasks.update(context,task.record.id,{title:"Preview only"},{dryRun:true});expect(preview.record.title).toBe("Preview only");expect(app.tasks.get(task.record.id)?.title).toBe("Follow up")});
 test("task mutations resolve relationships and own status dates",()=>{if(!app.gigs.get("task-gig"))app.gigs.create(context,{id:"task-gig",company:"Example",title:"VP Engineering",externalJobId:null,artifactDirectory:null,stage:"identified",outcome:"pending",statusSummary:"Found",lastActivity:"2026-08-01",nextAction:null,fit:{rating:"good",summary:null},payRange:null,sourceUrl:null,tags:[]});if(!app.people.get("task-person"))app.people.create(context,{id:"task-person",name:"Taylor Example",company:"Example",title:"Recruiter",linkedInProfileUrl:null,connectedOn:null});const created=app.tasks.createNew({...context,occurredAt:"2026-08-01T09:00:00-07:00",changeId:"task-create-change"},{id:"relationship-task",title:"Follow up",type:"networking_follow_up",priority:"high",dueDate:"2026-08-04",relatedEntity:{type:"person",id:"task-person"},notes:null});expect(created).toMatchObject({changeId:"task-create-change",record:{status:"open",completedAt:null,relatedEntity:{type:"person",id:"task-person",label:"Taylor Example"}}});const completed=app.tasks.update({...context,occurredAt:"2026-08-02T09:00:00-07:00",changeId:"task-update-change"},created.record.id,{status:"completed",relatedEntity:{type:"gig",id:"task-gig"}});expect(completed).toMatchObject({changeId:"task-update-change",record:{status:"completed",completedAt:"2026-08-02",relatedEntity:{type:"gig",id:"task-gig",label:"Example VP Engineering"}}});const reopened=app.tasks.update({...context,occurredAt:"2026-08-03T09:00:00-07:00"},created.record.id,{status:"in_progress"});expect(reopened.record).toMatchObject({status:"in_progress",completedAt:null});expect(()=>app.tasks.update(context,created.record.id,{relatedEntity:{type:"person",id:"missing"}})).toThrow("Person not found: missing")});
});
