import { describe,expect,test } from "bun:test";
import { JobSearchApplication } from "../src/application";
import { ChangeExecutor } from "../src/changes";
import { DomainValidationError,MutationError,OptimisticConcurrencyError } from "../src/errors";
import type { ArtifactPort,ArtifactVerification,AuditPort,DocumentWriteRepository,Persistence,ReadRepository,UnitOfWork } from "../src/ports";
import type { ChangeContext,EntityRecord,JobData,JobPersonData,MeetingData,MeetingParticipantData,NetworkingContactData,PersonData,TaskData } from "../src/models";
import { documentDisplayName,type DocumentLinkEntityType,type ManagedDocumentData,type ManagedDocumentRecord,type ManagedDocumentVersionData } from "../src/documents";

const metadata={revision:1,isDeleted:false,createdAt:"2026-07-22T12:00:00-07:00",updatedAt:"2026-07-22T12:00:00-07:00"};
class Repo<T extends{id:string}> implements ReadRepository<T>{rows=new Map<string,EntityRecord<T>>();get(id:string){return this.rows.get(id)??null}list(){return[...this.rows.values()]}create(record:T){const value={...record,...metadata};this.rows.set(record.id,value);return value}update(id:string,revision:number,patch:Partial<Omit<T,"id">>){const current=this.get(id)!;const value={...current,...patch,revision:revision+1,updatedAt:"2026-07-23T12:00:00-07:00"};this.rows.set(id,value);return value}delete(id:string){return this.rows.get(id)!}restore(id:string){return this.rows.get(id)!}}
const jobs=new Repo<JobData>(),people=new Repo<PersonData>(),networking=new Repo<NetworkingContactData>(),jobPeople=new Repo<JobPersonData>(),tasks=new Repo<TaskData>(),meetings=new Repo<MeetingData>(),meetingParticipants=new Repo<MeetingParticipantData>();
class DocumentRepo implements DocumentWriteRepository {
  rows=new Map<string,ManagedDocumentRecord>();histories=new Map<string,ManagedDocumentVersionData[]>();
  get(id:string){return this.rows.get(id)??null}
  list(entityType:DocumentLinkEntityType,entityId:string){return[...this.rows.values()].filter(document=>document.links.some(link=>link.entityType===entityType&&link.entityId===entityId))}
  listVersions(id:string){return this.histories.get(id)??[]}
  create(input:{document:ManagedDocumentData;content:string;contentHash:string}){const record={...input.document,displayName:documentDisplayName(input.document),currentVersion:1,content:input.content,contentHash:input.contentHash,createdAt:metadata.createdAt,updatedAt:metadata.updatedAt};this.rows.set(record.id,record);this.histories.set(record.id,[{documentId:record.id,version:1,parentVersion:null,content:record.content,contentHash:record.contentHash,changeId:"test-change",changeSummary:"change",createdAt:record.createdAt,createdBy:"test"}]);return record}
  addVersion(input:{documentId:string;expectedVersion:number;content:string;contentHash:string;changeSummary:string}){const current=this.get(input.documentId)!;const version=input.expectedVersion+1;const record={...current,currentVersion:version,content:input.content,contentHash:input.contentHash,updatedAt:"2026-07-23T12:00:00-07:00"};this.rows.set(record.id,record);this.histories.set(record.id,[{documentId:record.id,version,parentVersion:input.expectedVersion,content:record.content,contentHash:record.contentHash,changeId:"test-change",changeSummary:input.changeSummary,createdAt:record.updatedAt,createdBy:"test"},...(this.histories.get(record.id)??[])]);return record}
}
const documents=new DocumentRepo();
const recordedEvents:string[]=[];
const persistence:Persistence={jobs,people,networking,jobPeople,tasks,meetings,meetingParticipants,documents,change:(context,action)=>({changeId:context.changeId??`test-${context.summary}`,value:action({jobs,people,networking,jobPeople,tasks,meetings,meetingParticipants,documents,recordEvent:event=>{recordedEvents.push(event.id??event.type);return event.id??event.type}} as UnitOfWork)}),revertChange:(revertContext,targetChangeId)=>({changeId:revertContext.changeId??`revert-${targetChangeId}`,value:[{entity:"job",id:"job"}]})};
const artifacts:ArtifactPort={jobDescription:async()=>"description",interviewPrep:async()=>[{name:"general.md",content:"prep"}],jobDescriptionExists:async()=>true,interviewPrepExists:async()=>true,verify:async():Promise<ArtifactVerification>=>({ok:true,errors:[],unregistered:[]})};
const audit:AuditPort={query:query=>({query})};const app=new JobSearchApplication(persistence,audit,artifacts);const context:ChangeContext={actor:"test",source:"test",summary:"change"};
describe("application services",()=>{
 test("job service reads, writes, and loads artifacts",async()=>{app.jobs.create(context,{id:"job",company:"Company",title:"VP",jobId:null,roleDirectory:null,stage:"identified",outcome:"pending",statusSummary:"Found",lastActivity:"2026-07-22",nextAction:null,fit:{rating:"good",summary:null},payRange:null,sourceUrl:null,tags:[],hasJobDescription:true,hasInterviewPrep:true});expect(app.jobs.get("job")?.company).toBe("Company");expect(await app.jobs.description("job")).toBe("description");expect(await app.jobs.prep("job")).toHaveLength(1)});
 test("people service stores canonical people",()=>{app.people.create(context,{id:"person",name:"Person",company:null,title:null,linkedInProfileUrl:null,connectedOn:null});expect(app.people.get("person")?.name).toBe("Person")});
 test("networking service composes a person with outreach state",()=>{app.networking.create(context,{id:"network-person",name:"Network Person",company:null,title:null,linkedInProfileUrl:null,profileStatus:"missing",connectedOn:null,relationship:{type:"colleague",strength:"warm",introducedBy:null,notes:null},priority:"high",status:"not_contacted",outreach:{lastContacted:null,lastContactMethod:null,lastContactSummary:null,nextAction:null,nextActionDue:null},whyInteresting:null,notes:[],tags:[],source:{files:[]},createdAt:"2026-07-22",updatedAt:"2026-07-22"});expect(app.networking.get("network-person")?.name).toBe("Network Person")});
 test("task service creates and updates tasks",()=>{const created=app.tasks.createNew(context,{id:"task",title:"Task",type:"other",dueDate:null,relatedEntity:{type:"general",id:null,label:"General"},date:"2026-07-22"});expect(app.tasks.complete(context,created.id,"2026-07-22").status).toBe("completed")});
 test("meeting service stores meetings",()=>{if(!people.get("person"))people.create({id:"person",name:"Person",company:null,title:null,linkedInProfileUrl:null,connectedOn:null});app.meetings.create(context,{id:"meeting",title:"Coffee",startsAt:"2026-07-22T12:00:00-07:00",endsAt:"2026-07-22T13:00:00-07:00",timezone:"America/Los_Angeles",location:null,description:null,status:"confirmed",jobId:null,personIds:["person"],externalCalendarId:null,externalEventId:null});expect(app.meetings.list()).toHaveLength(1)});
 test("meeting participant IDs remain distinct when domain IDs contain delimiters",()=>{people.create({id:"b::c",name:"First Person",company:null,title:null,linkedInProfileUrl:null,connectedOn:null});people.create({id:"c",name:"Second Person",company:null,title:null,linkedInProfileUrl:null,connectedOn:null});const base={title:"Conversation",startsAt:"2026-07-22T12:00:00-07:00",endsAt:"2026-07-22T13:00:00-07:00",timezone:"America/Los_Angeles",location:null,description:null,status:"confirmed" as const,jobId:null,externalCalendarId:null,externalEventId:null};app.meetings.create(context,{...base,id:"a",personIds:["b::c"]});app.meetings.create(context,{...base,id:"a::b",personIds:["c"]});expect(meetingParticipants.list().filter(record=>record.meetingId==="a"||record.meetingId==="a::b").map(record=>record.id).sort()).toEqual(["meeting-participant:1:ab::c","meeting-participant:4:a::bc"])});
 test("meeting creation compares start and end as absolute instants",()=>{if(!people.get("timestamp-person"))people.create({id:"timestamp-person",name:"Timestamp Person",company:null,title:null,linkedInProfileUrl:null,connectedOn:null});const base={title:"Offset meeting",timezone:"America/Los_Angeles",location:null,description:null,status:"confirmed" as const,jobId:null,personIds:["timestamp-person"],externalCalendarId:null,externalEventId:null};expect(()=>app.meetings.create(context,{...base,id:"valid-offset-meeting",startsAt:"2026-07-20T23:00:00+09:00",endsAt:"2026-07-20T08:00:00-07:00"})).not.toThrow();expect(()=>app.meetings.create(context,{...base,id:"invalid-offset-meeting",startsAt:"2026-07-20T08:00:00-07:00",endsAt:"2026-07-20T23:00:00+09:00"})).toThrow("must end at or after it starts");expect(()=>app.meetings.create(context,{...base,id:"invalid-timestamp-meeting",startsAt:"not-a-date",endsAt:"2026-07-20T23:00:00+09:00"})).toThrow("requires valid ISO 8601 timestamps")});
 test("job-people service filters relationships",()=>{app.jobPeople.create(context,{id:"relation",jobId:"job",personId:"person",relationship:"interviewer",notes:null});const result=app.jobPeople.query({jobIds:["job"]});expect(result.status==="ok"?result.items:[]).toHaveLength(1)});
 test("event service records sourced business events",()=>{expect(app.events.record(context,{id:"event",type:"message_received",entityType:"job",entityId:"job",occurredAt:"2026-07-22T12:00:00-07:00",summary:"Recruiter wrote",sources:[{sourceSystem:"linkedin",importedAt:"2026-07-22T12:00:00-07:00"}]})).toBe("event");expect(recordedEvents).toContain("event")});
 test("history service delegates audit queries",()=>{expect(app.history.entity("job","job")).toBeTruthy()});
 test("managed document service creates immutable versions and deduplicates identical content",async()=>{
  if(!app.jobs.get("job"))app.jobs.create(context,{id:"job",company:"Company",title:"VP",jobId:null,roleDirectory:null,stage:"identified",outcome:"pending",statusSummary:"Found",lastActivity:"2026-07-22",nextAction:null,fit:{rating:"good",summary:null},payRange:null,sourceUrl:null,tags:[],hasJobDescription:true,hasInterviewPrep:true});
  const created=app.documents.create({...context,changeId:"document-create"},{links:[{entityType:"job",entityId:"job"}],documentType:"job_description",title:"Job description",mediaType:"text/plain",sourceDescription:"Provided by the user",content:"Original description"});
  expect(created).toMatchObject({changed:true,changeId:"document-create",document:{currentVersion:1,content:"Original description"}});
  const jobDetail=app.jobs.read("job");
  expect(jobDetail.status).toBe("ok");
  expect(jobDetail.status==="ok" ? jobDetail.record.documents : []).toContainEqual(expect.objectContaining({id:created.document.id,type:"job_description"}));
  expect(await app.documentReader.get(created.document.id)).toMatchObject({status:"ok",record:{content:"Original description"}});
  const unchanged=app.documents.update({...context,changeId:"document-noop"},{documentId:created.document.id,expectedVersion:1,content:"Original description",changeSummary:"No content change"});
  expect(unchanged).toMatchObject({changed:false,changeId:null,document:{currentVersion:1}});
  const updated=app.documents.update({...context,changeId:"document-update"},{documentId:created.document.id,expectedVersion:1,content:"Corrected description",changeSummary:"Correct source text"});
  expect(updated).toMatchObject({changed:true,changeId:"document-update",document:{currentVersion:2,content:"Corrected description"}});
  expect(app.documents.versions(created.document.id).map(version=>version.content)).toEqual(["Corrected description","Original description"]);
  expect(await app.documentReader.get(created.document.id)).toMatchObject({status:"ok",record:{content:"Corrected description"}});
 expect(()=>app.documents.update(context,{documentId:created.document.id,expectedVersion:1,content:"Stale description",changeSummary:"Stale update"})).toThrow(new MutationError("revision_conflict",`Document ${created.document.id} expected version 1 but is at version 2.`));
 });
 test("uploaded source documents preserve provenance and cannot be edited",()=>{
  if(!app.jobs.get("job"))app.jobs.create(context,{id:"job",company:"Company",title:"VP",jobId:null,roleDirectory:null,stage:"identified",outcome:"pending",statusSummary:"Found",lastActivity:"2026-07-22",nextAction:null,fit:{rating:"good",summary:null},payRange:null,sourceUrl:null,tags:[],hasJobDescription:true,hasInterviewPrep:true});
  const provenance={originalFilename:"role.pdf",detectedMediaType:"application/pdf" as const,sourceContentHash:"a".repeat(64),converter:"pdfjs-dist",converterVersion:"6.2.108",extractionWarnings:[],uploadedAt:"2026-07-29T12:00:00.000Z"};
  const created=app.documents.create({...context,changeId:"uploaded-document-create"},{links:[{entityType:"job",entityId:"job"}],documentType:"job_description",title:"Uploaded job description",mediaType:"text/markdown",sourceDescription:null,content:"Exact converted source",uploadProvenance:provenance});
  expect(created.document.uploadProvenance).toEqual(provenance);
  expect(()=>app.documents.update(context,{documentId:created.document.id,expectedVersion:1,content:"Rewritten source",changeSummary:"Rewrite"})).toThrow(new DomainValidationError("Uploaded source documents are immutable and cannot be updated."));
 });
 test("profiles link to exactly one person and appear on every related record",()=>{
  if(!app.jobs.get("job"))app.jobs.create(context,{id:"job",company:"Company",title:"VP",jobId:null,roleDirectory:null,stage:"identified",outcome:"pending",statusSummary:"Found",lastActivity:"2026-07-22",nextAction:null,fit:{rating:"good",summary:null},payRange:null,sourceUrl:null,tags:[]});
  const contact=app.networking.get("network-person")??app.networking.create(context,{id:"network-person",name:"Network Person",company:"Company",title:"Director",linkedInProfileUrl:null,profileStatus:"missing",connectedOn:null,relationship:{type:"colleague",strength:"warm",introducedBy:null,notes:null},priority:"high",status:"active_relationship",outreach:{lastContacted:null,lastContactMethod:null,lastContactSummary:null,nextAction:null,nextActionDue:null},whyInteresting:null,notes:[],tags:[],source:{files:[]},createdAt:"2026-07-22",updatedAt:"2026-07-22"});
  const created=app.documents.create(context,{links:[{entityType:"person",entityId:contact.personId},{entityType:"job",entityId:"job"}],documentType:"profile",title:null,mediaType:"text/markdown",sourceDescription:null,content:"Person profile"});
  expect(created.document.displayName).toBe("Profile");
  expect(app.jobs.get("job")?.documents).toContainEqual({id:created.document.id,type:"profile",title:null,displayName:"Profile"});
  expect(app.networking.get(contact.id)).toMatchObject({hasProfile:true,documents:[{id:created.document.id,type:"profile",title:null,displayName:"Profile"}]});
  expect(()=>app.documents.create(context,{links:[{entityType:"job",entityId:"job"}],documentType:"profile",title:null,mediaType:"text/markdown",sourceDescription:null,content:"Missing person"})).toThrow(new DomainValidationError("A profile must link to exactly one person."));
 });
 test("shared job service returns complete models and preserves fields on patch",()=>{const role=app.jobs.create(context,{id:"complete-job",company:"Company",title:"VP Engineering",jobId:"123",roleDirectory:null,stage:"identified",outcome:"pending",statusSummary:"Found",lastActivity:"2026-07-22",nextAction:null,fit:{rating:"good",summary:null},payRange:null,sourceUrl:null,tags:[],hasJobDescription:false,hasInterviewPrep:false,location:"Seattle",workArrangement:"hybrid",postedDate:"2026-07-20",businessUnitTeam:"Platform",recruiterSource:"Referral",bonus:"20%",equity:"RSUs",otherCompensation:null});expect(role.location).toBe("Seattle");const updated=app.jobs.update(context,role.id,{stage:"applied",statusSummary:"Applied"});expect(updated.record).toMatchObject({stage:"applied",location:"Seattle",workArrangement:"hybrid",bonus:"20%",equity:"RSUs"});expect(updated.changeId).toBe("test-change");expect(jobs.get(role.id)).toMatchObject({location:"Seattle",workArrangement:"hybrid",bonus:"20%",equity:"RSUs"})});
 test("job updates return the caller-supplied audited change",()=>{app.jobs.create(context,{id:"updated-job",company:"Company",title:"Director",jobId:null,roleDirectory:null,stage:"identified",outcome:"pending",statusSummary:"Found",lastActivity:"2026-07-22",nextAction:null,fit:{rating:"good",summary:null},payRange:null,sourceUrl:null,tags:[]});const result=app.jobs.update({...context,changeId:"change-1"},"updated-job",{stage:"applied",statusSummary:"Applied"});expect(result).toMatchObject({changeId:"change-1",record:{stage:"applied",statusSummary:"Applied"}});expect(app.jobs.get("updated-job")?.stage).toBe("applied")});
 test("dry-run updates return a candidate without an audit change",()=>{app.jobs.create(context,{id:"preview-job",company:"Company",title:"Director",jobId:null,roleDirectory:null,stage:"identified",outcome:"pending",statusSummary:"Found",lastActivity:"2026-07-22",nextAction:null,fit:{rating:"good",summary:null},payRange:null,sourceUrl:null,tags:[]});const result=app.jobs.update(context,"preview-job",{statusSummary:"Preview"},{dryRun:true});expect(result).toMatchObject({changeId:null,record:{statusSummary:"Preview"}});expect(app.jobs.get("preview-job")?.statusSummary).toBe("Found")});
 test("change reversal is a client-neutral application capability",()=>{expect(app.changes.revert({actor:"candidate",source:"user_request",summary:"Undo update",changeId:"revert-1"},"change-from-cli")).toEqual({changeId:"revert-1",revertedChangeId:"change-from-cli",affected:[{entity:"job",id:"job"}]})});
 test("change execution translates persistence concurrency failures",()=>{const conflictPersistence={...persistence,change:()=>{throw new OptimisticConcurrencyError("Job job expected revision 1, actual revision 2")}} satisfies Persistence;const executor=new ChangeExecutor(conflictPersistence);try{executor.execute(context,{id:"job"},{},()=>({id:"job"}));throw new Error("Expected conflict")}catch(error){expect(error).toBeInstanceOf(MutationError);expect((error as MutationError).code).toBe("revision_conflict");expect((error as Error).cause).toBeInstanceOf(OptimisticConcurrencyError)}});
 test("rejects contradictory job stage and outcome states with clear domain errors",()=>{const role={id:"invalid-job",company:"Company",title:"VP Engineering",jobId:null,roleDirectory:null,stage:"identified" as const,outcome:"pending" as const,statusSummary:"Found",lastActivity:"2026-07-22",nextAction:null,fit:{rating:"good" as const,summary:null},payRange:null,sourceUrl:null,tags:[],hasJobDescription:false,hasInterviewPrep:false};expect(()=>app.jobs.create(context,{...role,stage:"closed"})).toThrow(new DomainValidationError("Job invalid-job cannot be closed while its outcome is pending."));expect(()=>app.jobs.create(context,{...role,outcome:"rejected"})).toThrow(new DomainValidationError("Job invalid-job must remain pending until its stage is closed."))});
 test("shared contact service updates atomically and returns persisted state",()=>{const contact=app.networking.create(context,{id:"shared-contact",name:"Shared Contact",company:"Company",title:"Director",linkedInProfileUrl:null,profileStatus:"missing",connectedOn:null,relationship:{type:"former_colleague",strength:"warm",introducedBy:null,notes:null},priority:"high",status:"not_contacted",outreach:{lastContacted:null,lastContactMethod:null,lastContactSummary:null,nextAction:null,nextActionDue:null},whyInteresting:null,notes:[],tags:[],source:{files:[]},createdAt:"2026-07-22",updatedAt:"2026-07-22"});const updated=app.networking.update(context,contact.id,{status:"outreach_sent",outreach:{lastContacted:"2026-07-23",lastContactMethod:"linkedin",lastContactSummary:"Sent a note"}});const persisted=app.networking.get(contact.id);if(!persisted)throw new Error("Expected persisted contact");expect(updated.record.outreach.lastContactSummary).toBe("Sent a note");expect(updated.record.updatedAt).toBe("2026-07-23");expect(updated.record).toEqual(persisted);expect(people.get(contact.id)?.name).toBe("Shared Contact");expect(networking.get(contact.id)?.status).toBe("outreach_sent")});
 test("shared task service owns defaults, completion, and dry runs",()=>{const task=app.tasks.createNew(context,{id:"shared-task",title:"Follow up",type:"networking_follow_up",dueDate:"2026-07-24",relatedEntity:{type:"general",id:null,label:"General"},date:"2026-07-22"});expect(task).toMatchObject({status:"open",priority:"medium"});expect(app.tasks.complete(context,task.id,"2026-07-23")).toMatchObject({status:"completed",completedAt:"2026-07-23"});const preview=app.tasks.update(context,task.id,{title:"Preview only"},{dryRun:true});expect(preview.title).toBe("Preview only");expect(app.tasks.get(task.id)?.title).toBe("Follow up")});
});
