import type { Persistence } from "./ports";
import type { ChangeContext, EntityRecord, InteractionData, InteractionParticipantData } from "./models";
import type { GigRecord } from "./gigs";
import type { PeopleService } from "./services";
import type { Interaction, InteractionInput, InteractionRecord } from "./interactions";
import { interactionEntitySchema, interactionInputSchema, interactionInstant, interactionParticipantId } from "./interactions";
import type { InteractionQueryInput, PageResult, ReadResult } from "./queries";
import { matchesQuery, normalizedQuery, page } from "./queries";
import { DomainValidationError } from "./errors";
import type { ChangeExecutor, MutationOptions, MutationResult } from "./changes";

/* eslint-disable @typescript-eslint/no-unused-expressions */

interface GigReads { read(id:string): ReadResult<GigRecord> }
export class InteractionService {
  constructor(private readonly persistence:Persistence,private readonly gigs:GigReads,private readonly people:PeopleService,private readonly changes:ChangeExecutor){}
  get(id:string):InteractionRecord|null { const result=this.read(id);if(result.status==="not_found")return null;if(result.status==="consistency_error")throw new DomainValidationError(result.message);return result.record }
  list():InteractionRecord[]{return this.persistence.interactions.list().map(raw=>{const result=this.compose(raw);if(result.status!=="ok")throw new DomainValidationError(result.status==="consistency_error"?result.message:`Interaction ${raw.id} was not found.`);return result.record})}
  read(id:string):ReadResult<InteractionRecord>{const raw=this.persistence.interactions.get(id);return raw?this.compose(raw):{status:"not_found",id}}
  query(input:InteractionQueryInput):PageResult<InteractionRecord>{const from=input.startsFrom===undefined?undefined:this.parseInstant(input.startsFrom,"startsFrom"),through=input.startsThrough===undefined?undefined:this.parseInstant(input.startsThrough,"startsThrough");if(from!==undefined&&through!==undefined&&from>through)throw new DomainValidationError("Interaction startsFrom must not be after startsThrough.");const query=normalizedQuery(input.query);return{status:"ok",...page(this.list().filter(r=>input.personIds===undefined||r.personIds.some(id=>input.personIds!.includes(id))).filter(r=>input.gigIds===undefined||(r.gigId!==null&&input.gigIds.includes(r.gigId))).filter(r=>input.kinds===undefined||input.kinds.includes(r.kind)).filter(r=>input.channels===undefined||input.channels.includes(r.channel)).filter(r=>input.directions===undefined||input.directions.includes(r.direction)).filter(r=>input.statuses===undefined||input.statuses.includes(r.status)).filter(r=>from===undefined||Date.parse(r.startsAt)>=from).filter(r=>through===undefined||Date.parse(r.startsAt)<=through).filter(r=>matchesQuery(query,[r.subject,r.summary,r.notes,r.location])).sort((a,b)=>Date.parse(b.startsAt)-Date.parse(a.startsAt)||a.id.localeCompare(b.id)),input)}}
  create(context:ChangeContext,id:string,input:InteractionInput,options:MutationOptions={}):MutationResult<InteractionRecord>{const parsed=interactionInputSchema.parse(input);const candidate=interactionEntitySchema.parse({id,subject:parsed.subject??"",kind:parsed.kind??"other",channel:parsed.channel??"other",direction:parsed.direction??"unknown",status:parsed.status??"completed",startsAt:parsed.startsAt??"",endsAt:parsed.endsAt??null,timezone:parsed.timezone??null,location:parsed.location??null,summary:parsed.summary??null,notes:parsed.notes??null,personIds:parsed.personIds??[],gigId:parsed.gigId??null,supersedesInteractionId:parsed.supersedesInteractionId??null,originChangeId:parsed.originChangeId??null,structuredData:parsed.structuredData??{}});this.validateReferences(candidate);const timestamp=context.occurredAt??new Date().toISOString(),preview:InteractionRecord={...candidate,revision:1,isDeleted:false,createdAt:timestamp,updatedAt:timestamp};return this.changes.execute<InteractionRecord>(context,preview,options,tx=>{const{personIds,structuredData,...rest}=candidate;const record=tx.interactions.create({...rest,structuredDataJson:JSON.stringify(structuredData)},{reversible:true});for(const personId of personIds)tx.interactionParticipants.create(this.participant(id,personId),{reversible:true});return this.fromStored(record,structuredData,[...personIds].sort())})}
  update(context:ChangeContext,id:string,input:InteractionInput,options:MutationOptions={}):MutationResult<InteractionRecord>{const patch=interactionInputSchema.parse(input),current=this.get(id);if(!current)throw new Error(`Interaction not found: ${id}`);const{revision:_,isDeleted:__,createdAt:___,updatedAt:____,...entity}=current;const candidate=interactionEntitySchema.parse({...entity,...patch,personIds:patch.personIds??current.personIds});this.validateReferences(candidate);const preview:InteractionRecord={...current,...candidate};const raw=this.persistence.interactions.get(id)!,participants=this.persistence.interactionParticipants.list().filter(p=>p.interactionId===id),wanted=new Set(candidate.personIds);const{personIds:_____,structuredData,...rest}=patch;const dataPatch={...rest,...(structuredData===undefined?{}:{structuredDataJson:JSON.stringify(structuredData)})};return this.changes.execute<InteractionRecord>(context,preview,options,tx=>{const persisted=Object.keys(dataPatch).length?tx.interactions.update(id,raw.revision,dataPatch):tx.interactions.touch(id,raw.revision);for(const p of participants)if(!wanted.has(p.personId))tx.interactionParticipants.delete(p.id,p.revision);for(const personId of candidate.personIds)if(!participants.some(p=>p.personId===personId)){const data=this.participant(id,personId),previous=this.persistence.interactionParticipants.get(data.id,{includeDeleted:true});previous?.isDeleted?tx.interactionParticipants.restore(data.id,previous.revision,data):tx.interactionParticipants.create(data,{reversible:true})}return this.fromStored(persisted,candidate.structuredData,[...candidate.personIds].sort())})}
  delete(context:ChangeContext,id:string,expectedRevision:number,options:MutationOptions={}):MutationResult<InteractionRecord>{const current=this.get(id);if(!current)throw new Error(`Interaction not found: ${id}`);if(current.revision!==expectedRevision)throw new DomainValidationError(`Interaction ${id} revision conflict.`);const preview:InteractionRecord={...current,isDeleted:true,revision:current.revision+1};return this.changes.execute<InteractionRecord>(context,preview,options,tx=>{for(const p of this.persistence.interactionParticipants.list().filter(p=>p.interactionId===id))tx.interactionParticipants.delete(p.id,p.revision);const record=tx.interactions.delete(id,expectedRevision);return this.fromStored(record,current.structuredData,current.personIds)})}
  private compose(raw:EntityRecord<InteractionData>):ReadResult<InteractionRecord>{let structuredData:Record<string,unknown>;try{structuredData=JSON.parse(raw.structuredDataJson)}catch{return{status:"consistency_error",id:raw.id,message:`Interaction ${raw.id} has invalid structured data.`}}const participants=this.persistence.interactionParticipants.list().filter(p=>p.interactionId===raw.id).sort((a,b)=>a.personId.localeCompare(b.personId));const candidate=this.fromStored(raw,structuredData,participants.map(p=>p.personId));const{revision:_,isDeleted:__,createdAt:___,updatedAt:____,...entity}=candidate;const parsed=interactionEntitySchema.safeParse(entity);if(!parsed.success)return{status:"consistency_error",id:raw.id,message:`Interaction ${raw.id} is invalid: ${parsed.error.issues[0]?.message}`};return{status:"ok",record:candidate}}
  private fromStored(raw:EntityRecord<InteractionData>,structuredData:Record<string,unknown>,personIds:string[]):InteractionRecord{const{structuredDataJson:_,...record}=raw;return{...record,kind:raw.kind as Interaction["kind"],channel:raw.channel as Interaction["channel"],direction:raw.direction as Interaction["direction"],status:raw.status as Interaction["status"],structuredData,personIds}}
  private validateReferences(value:Interaction){for(const personId of value.personIds)if(this.people.read(personId).status!=="ok")throw new DomainValidationError(`Interaction ${value.id} references missing person ${personId}.`);if(value.gigId&&this.gigs.read(value.gigId).status!=="ok")throw new DomainValidationError(`Interaction ${value.id} references missing gig ${value.gigId}.`);if(value.supersedesInteractionId){let next:string|null=value.supersedesInteractionId;const seen=new Set([value.id]);while(next){if(seen.has(next))throw new DomainValidationError(`Interaction ${value.id} creates a supersession cycle.`);seen.add(next);const prior=this.get(next);if(!prior)throw new DomainValidationError(`Interaction ${value.id} references missing superseded Interaction ${next}.`);next=prior.supersedesInteractionId}}}
  private participant(interactionId:string,personId:string):InteractionParticipantData{return{id:interactionParticipantId(interactionId,personId),interactionId,personId}}
  private parseInstant(value:string,field:string){const result=interactionInstant(value);if(result===null)throw new DomainValidationError(`Interaction ${field} must be a valid ISO 8601 timestamp.`);return result}
}
