import type { NormalizedPosition, SourceConfiguration } from "../contracts";
import { normalizeDescription } from "../descriptions";

type PlatformSource=Extract<SourceConfiguration,{type:"platform"}>;
type Json=Record<string,unknown>;
const object=(value:unknown):Json=>value&&typeof value==="object"&&!Array.isArray(value)?value as Json:{};
const array=(value:unknown):unknown[]=>Array.isArray(value)?value:[];
const arrayField=(value:Json,key:string)=>Object.hasOwn(value,key)&&Array.isArray(value[key])?value[key] as unknown[]:null;
const text=(value:unknown)=>typeof value==="string"?value:"";
const scalar=(value:unknown)=>typeof value==="string"||typeof value==="number"?String(value):"";
const absolute=(value:string,base:string)=>{try{return new URL(value,base).toString();}catch{return "";}};
const locationObject=(value:unknown)=>text(object(value).name)||text(object(value).fullLocation);
const position=(source:PlatformSource,value:{id?:unknown;title?:unknown;url?:unknown;location?:unknown;description?:unknown}):NormalizedPosition|null=>{const title=text(value.title).trim(),url=absolute(text(value.url),source.url);if(!title||!url)return null;const description=normalizeDescription(value.description);return{sourceKey:source.key,externalId:scalar(value.id)||null,canonicalUrl:url,title,location:text(value.location).trim()||null,description,provenance:{sourceKey:source.key,sourceUrl:source.url,description:description?"listing":"none"}};};

export function platformRequest(source:PlatformSource,page:number){
  const configured=new URL(source.url);const term=source.searchTerms[(page-1)%Math.max(1,source.searchTerms.length)]??"";
  switch(source.adapter){
    case"greenhouse":{if(configured.hostname==="boards-api.greenhouse.io")return{url:configured.toString(),method:"GET" as const};const board=configured.pathname.split("/").filter(Boolean)[0];return{url:`https://boards-api.greenhouse.io/v1/boards/${board}/jobs?content=true`,method:"GET" as const};}
    case"lever":{if(configured.hostname==="api.lever.co")return{url:configured.toString(),method:"GET" as const};const company=configured.pathname.split("/").filter(Boolean)[0];return{url:`https://api.lever.co/v0/postings/${company}?mode=json`,method:"GET" as const};}
    case"smartrecruiters":{if(configured.hostname==="api.smartrecruiters.com"){configured.searchParams.set("offset",String((page-1)*100));return{url:configured.toString(),method:"GET" as const};}const company=configured.pathname.split("/").filter(Boolean)[0];return{url:`https://api.smartrecruiters.com/v1/companies/${company}/postings?limit=100&offset=${(page-1)*100}`,method:"GET" as const};}
    case"ashby":{if(configured.hostname==="api.ashbyhq.com")return{url:configured.toString(),method:"GET" as const};const organization=configured.pathname.split("/").filter(Boolean)[0];return{url:`https://api.ashbyhq.com/posting-api/job-board/${organization}`,method:"GET" as const};}
    case"workday":{const parts=configured.pathname.split("/").filter(Boolean);const cxs=parts.indexOf("cxs");let tenant=parts[cxs+1],site=parts[cxs+2];if(!tenant||!site){tenant=configured.hostname.split(".")[0];site=parts.find(part=>!part.match(/^[a-z]{2}-[A-Z]{2}$/));}return{url:new URL(`/wday/cxs/${tenant}/${site}/jobs`,configured.origin).toString(),method:"POST" as const,body:JSON.stringify({appliedFacets:{},limit:20,offset:(page-1)*20,searchText:term})};}
    case"oracle-hcm":{if(configured.pathname.includes("/hcmRestApi/resources/")){configured.searchParams.set("offset",String((page-1)*25));return{url:configured.toString(),method:"GET" as const};}const parts=configured.pathname.split("/").filter(Boolean);const index=parts.indexOf("sites"),site=parts[index+1]??"CX_1";const url=new URL("/hcmRestApi/resources/latest/recruitingCEJobRequisitions",configured.origin);url.searchParams.set("onlyData","true");url.searchParams.set("limit","25");url.searchParams.set("offset",String((page-1)*25));url.searchParams.set("expand","all");url.searchParams.set("finder",`findReqs;siteNumber=${site.startsWith("CX_")?site:"CX_1"},keyword=${term}`);return{url:url.toString(),method:"GET" as const};}
    case"adp":{if(configured.pathname.startsWith("/public/staffing/v1/career-site/")){const url=new URL(configured);if(!url.pathname.endsWith("/requisitions"))url.pathname+=`/requisitions`;url.searchParams.set("offset",String((page-1)*20));url.searchParams.set("limit","20");return{url:url.toString(),method:"GET" as const};}const domain=configured.pathname.split("/").filter(Boolean)[0];return{url:new URL(`/public/staffing/v1/career-site/${domain}/requisitions?offset=${(page-1)*20}&limit=20`,configured.origin).toString(),method:"GET" as const};}
    case"eightfold":{const domain=configured.searchParams.get("domain")??"";const url=new URL("/api/pcsx/search",configured.origin);url.searchParams.set("domain",domain);url.searchParams.set("query",term);url.searchParams.set("start",String((page-1)*10));url.searchParams.set("num","10");return{url:url.toString(),method:"GET" as const};}
    case"jibe":{const url=new URL("/api/jobs",configured.origin);url.searchParams.set("keywords",term);url.searchParams.set("page",String(page));return{url:url.toString(),method:"GET" as const};}
    case"successfactors-rmk":{const url=new URL(configured);url.searchParams.set("pageNumber",String(page-1));return{url:url.toString(),method:"GET" as const};}
    case"gem":{const board=new URLSearchParams(configured.hash.slice(1)).get("gem-board-id")??configured.pathname.split("/").filter(Boolean)[0]??"";return{url:"https://jobs.gem.com/api/public/graphql",method:"POST" as const,body:JSON.stringify({operationName:"JobBoardList",variables:{boardId:board},query:"query JobBoardList($boardId:String!){oatsExternalJobPostings(boardId:$boardId){jobPostings{id extId title descriptionHtml locations{name city isRemote}}}}"})};}
  }
}

export function extractPlatform(source:PlatformSource,body:string):{positions:NormalizedPosition[];hasNext:boolean;surfaceVerified:boolean}{
  const root:unknown=JSON.parse(body);const data=object(root);let records:unknown[]=[];let total=0;let surfaceVerified=false;
switch(source.adapter){case"greenhouse":{const found=arrayField(data,"jobs");surfaceVerified=found!==null;records=found??[];break;}case"lever":surfaceVerified=Array.isArray(root);records=array(root);break;case"smartrecruiters":{const found=arrayField(data,"content");surfaceVerified=found!==null;records=found??[];total=Number(data.totalFound??0);break;}case"ashby":{const found=arrayField(data,"jobs");surfaceVerified=found!==null;records=found??[];break;}case"workday":{const found=arrayField(data,"jobPostings");surfaceVerified=found!==null;records=found??[];total=Number(data.total??0);break;}case"oracle-hcm":{const items=arrayField(data,"items");surfaceVerified=items!==null&&items.every(item=>arrayField(object(item),"requisitionList")!==null);records=(items??[]).flatMap(item=>arrayField(object(item),"requisitionList")??[]);total=Number(data.count??0);break;}case"adp":{const found=arrayField(data,"jobRequisitions")??arrayField(data,"requisitions");surfaceVerified=found!==null;records=found??[];total=Number(data.totalCount??0);break;}case"eightfold":{const found=arrayField(data,"positions")??arrayField(data,"data");surfaceVerified=found!==null;records=found??[];total=Number(data.total??0);break;}case"jibe":{const found=arrayField(data,"jobs")??arrayField(data,"results");surfaceVerified=found!==null;records=found??[];total=Number(data.total??data.totalCount??0);break;}case"successfactors-rmk":{const found=arrayField(data,"searchResults")??arrayField(data,"results");surfaceVerified=found!==null;records=found??[];total=Number(data.totalResults??0);break;}case"gem":{const postings=object(object(data.data).oatsExternalJobPostings);const found=arrayField(postings,"jobPostings");surfaceVerified=found!==null;records=found??[];break;}}
  if(source.adapter==="jibe"||source.adapter==="successfactors-rmk"||source.adapter==="gem"){
    const positions=records.flatMap((entry):NormalizedPosition[]=>{const item=object(entry);if(source.adapter==="jibe"){const candidate=position(source,{id:item.id??item.reqId,title:item.title??item.name,url:item.url??item.jobUrl??item.applyUrl,location:text(item.location)||locationObject(item.locations),description:item.description});return candidate?[candidate]:[];}if(source.adapter==="successfactors-rmk"){const posting=object(item.response??item);const id=scalar(posting.id);const title=text(posting.unifiedStandardTitle??posting.title);const url=text(posting.url??posting.jobUrl)||absolute(`/job/${id}`,source.url);const locations=(array(posting.jobLocationShort).length?array(posting.jobLocationShort):array(posting.jobLocationCountry)).join("; ")||text(posting.location);const candidate=position(source,{id,title,url,location:locations});return candidate?[candidate]:[];}const locations=array(item.locations).map(value=>{const location=object(value),label=text(location.name)||text(location.city);return location.isRemote&&!/remote/i.test(label)?`${label||"Remote"} (Remote)`:label;}).filter(Boolean).join("; ");const candidate=position(source,{id:item.extId??item.id,title:item.title,url:item.url??`https://jobs.gem.com/job/${scalar(item.extId??item.id)}`,location:locations,description:item.descriptionHtml});return candidate?[candidate]:[];});return{positions,hasNext:total>records.length&&records.length>0,surfaceVerified};
  }
  // The three remaining adapters return from the specialized normalization block above.
  // eslint-disable-next-line @typescript-eslint/switch-exhaustiveness-check
  const positions=records.flatMap((entry):NormalizedPosition[]=>{const item=object(entry);let candidate:NormalizedPosition|null=null;switch(source.adapter){case"greenhouse":candidate=position(source,{id:item.id,title:item.title,url:item.absolute_url??item.url,location:locationObject(item.location),description:item.content});break;case"lever":candidate=position(source,{id:item.id,title:item.text,url:item.hostedUrl??item.applyUrl,location:text(object(item.categories).location),description:[text(item.description),...array(item.lists).map(value=>text(object(value).content)),text(item.additional)].filter(Boolean).join("\n\n")});break;case"smartrecruiters":candidate=position(source,{id:item.id,title:item.name,url:item.postingUrl??item.applyUrl??item.ref,location:locationObject(item.location),description:Object.values(object(object(item.jobAd).sections)).map(value=>text(object(value).text)).filter(Boolean).join("\n\n")});break;case"ashby":candidate=position(source,{id:item.id,title:item.title,url:item.jobUrl,location:[text(item.location),...array(item.secondaryLocations).map(value=>text(object(value).location))].filter(Boolean).join("; "),description:item.descriptionHtml});break;case"workday":candidate=position(source,{id:item.bulletFields?array(item.bulletFields)[0]:item.externalPath,title:item.title,url:item.externalPath,location:[text(item.locationsText),text(item.remoteType)].filter(Boolean).join(" - ")});break;case"oracle-hcm":candidate=position(source,{id:item.Id??item.RequisitionNumber,title:item.Title,url:item.ExternalCareerSiteURL??item.ExternalApplyURL,location:[text(item.PrimaryLocation),text(item.WorkplaceType)].filter(Boolean).join(" - "),description:[text(item.ShortDescriptionStr),text(item.ExternalQualificationsStr),text(item.ExternalResponsibilitiesStr)].filter(Boolean).join("\n\n")});break;case"adp":candidate=position(source,{id:item.reqId??item.clientRequisitionID,title:item.publishedJobTitle??item.jobTitle,url:item.jobUrl??item.applyUrl,location:array(item.requisitionLocations).map(value=>{const address=object(object(value).address??value);return[text(address.cityName),text(object(address.countrySubdivisionLevel1).shortName),text(object(address.country).longName)].filter(Boolean).join(", ");}).filter(Boolean).join("; "),description:[text(item.jobDescription),text(item.jobQualifications)].filter(Boolean).join("\n\n")});break;case"eightfold":candidate=position(source,{id:item.id,title:item.name,url:item.publicUrl??item.positionUrl,location:(array(item.standardizedLocations).length?array(item.standardizedLocations):array(item.locations)).join("; ")||text(item.location),description:item.jobDescription});break;}return candidate?[candidate]:[];});
  return{positions,hasNext:total>records.length&&records.length>0,surfaceVerified};
}
